sudo: required
language: generic
services: 
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t shinjs0505/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shinjs0505/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-229674681585"
  bucket_path: "docker-react"
  on:
    branche: master
      
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY